@extends('user.layout.app')
@section('content')
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{{ route('user-index') }}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span>Terms and Conditions
            </div>
        </div>
    </div>
    <div class="page-content pt-50">
        <div class="container">
            <div class="row">
                <div class="col-12 mx-auto">
                    <h1 class="text-center my-4">TERMS & CONDITIONS</h1>
                    <p class="my-3">This document is an electronic record in terms of Information Technology Act, 2000 and
                        rules there
                        under as applicable and the amended provisions pertaining to electronic records in various statutes
                        as amended by the Information Technology Act, 2000. This electronic record is generated by a
                        computer system and does not require any physical or digital signatures. This document is published
                        in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries
                        guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms
                        of Use for access or usage of Website. Accessing, browsing or otherwise using the site indicates
                        your agreement to all the terms and conditions under these terms of use.</p>

                </div>
            </div>
            <div class="row">
                <div class="col-12 mx-auto">
                    <ul>
                        <dl>
                            <li>
                                <h5>Agreement:</h5>
                                <dd>By accessing this Website, you agree to the following terms and conditions. If you do
                                    not
                                    agree, please exit this Website.</dd>
                            </li><br>
                            <li>
                                <h5>Definitions:</h5>
                                <dd>
                                    <ul>IPR: copyright, database rights and other intellectual property rights</ul>
                                    <ul>Attica Jewels: Attica Jewels Pvt Ltd., (also referred to as "we", "our" and "us")
                                    </ul>
                                    <ul>Public Materials: the Website Materials freely accessible to the public</ul>
                                    <ul>Restricted Materials: Website Material reserved to customers of Attica Jewels Pvt
                                        Ltd.</ul>
                                    <ul>Website Materials: Material displayed on or via this Website, which may include
                                        text,
                                        graphics, audio, photo or video conten</ul>
                                </dd>
                            </li><br>
                            <li>
                                <h5>Ownership:</h5>
                                <dd>The IPR for the Website Material are owned by or licensed to Attica Jewels Pvt Ltd., or
                                    the owners of third party web sites. The laws of India, international treaties and all
                                    other
                                    applicable copyright and intellectual property laws protect these IPRs. You agree to
                                    respect
                                    our IPR and those of third parties.</dd>
                            </li><br>
                            <li>
                                <h5>Copying:</h5>
                                <dd>
                                    <ul>You are authorised to download any number of copies of the Public Material for your
                                        own
                                        personal, non-commercial use, and may make such copies available to third parties
                                        provided that <br> (a) you acknowledge the source <br> (b) you do not remove or
                                        amend
                                        any
                                        trademark, copyright or other ownership notice, and <br> (c) each recipient agrees
                                        to
                                        these
                                        terms and conditions.</ul>
                                    <ul>The copying and use of third party website material accessed via this web-site is
                                        governed by the terms of use applicable to the third party site which you have
                                        accessed.
                                    </ul>
                                    <ul>Attica Jewels Pvt Ltd. reserves the right to take appropriate action against any
                                        violation of these terms.</ul>
                                </dd>
                            </li><br>
                            <li>
                                <h5>Restrictions:</h5>
                                <dd>You are expressly and emphatically prohibited from all of the following:
                                    <ul>deploying within our Website any spider, robot, web crawler or other automated query
                                        program</ul>
                                    <ul>publishing any Website material in any media</ul>
                                    <ul>re-using and/or aggregating a substantial or significant part of the Website
                                        Materials
                                        in the provision of a commercial service.</ul>
                                    <ul>selling, sublicensing and/or otherwise commercializing any Website material</ul>
                                    <ul>publicly performing and/or showing any Website material;</ul>
                                    <ul>using this Website in any way that is, or may be, damaging to this Website</ul>
                                    <ul>using this Website in any way that impacts user access to this Website</ul>
                                    <ul>using this Website contrary to applicable laws and regulations, or in a way that
                                        causes,
                                        or may cause, harm to the Website, or to any person or business entity</ul>
                                    <ul>engaging in any data mining, data harvesting, data extracting or any other similar
                                        activity in relation to this Website, or while using this Website</ul>
                                    <ul>using this Website to engage in any advertising or marketing</ul>
                                </dd>
                            </li><br>
                            <li>
                                <h5>Postings:</h5>
                                <dd></dd> All information (including but not limited to ideas, suggestions, concepts and
                                graphics) submitted to us through this Website will become our exclusive property. Except as
                                provided by applicable data privacy legislation, we shall not be subject to any obligation
                                of
                                confidentiality and will be free to use the information for any purpose.</dd>
                            </li><br>
                            <li>
                                <h5>Exclusions</h5>
                                <dd>
                                    <ul>(a) Warranty Exclusion: the public material is provided free of charge on an "as is"
                                        basis. To the fullest extent permitted by applicable law, we exclude all warranties,
                                        representations or understandings whatsoever, express or implied, including but not
                                        limited to warranties of satisfactory quality, merchantability, fitness for a
                                        particular
                                        purpose, freedom from computer viruses, and non-infringement of third parties'
                                        rights.
                                        We reserve the right at any time and without notice to change, amend or otherwise
                                        vary
                                        these terms and conditions and all web site material.</ul>
                                    <ul>(b) exclusion of liability: we shall not be liable for loss arising out of use of
                                        the
                                        public material, whether (a) direct or indirect, special, incidental or
                                        consequential
                                        loss or damage or <br> (b) any loss of profits, revenue, contracts, data, goodwill,
                                        work
                                        stoppage or computer failure. This exclusion of liability shall apply even if we
                                        have
                                        been advised of the possibility of such damages. We exclude any liability for any
                                        errors
                                        in or omissions from information, materials and functions included in the public
                                        materials. To the fullest extent permitted by applicable law. We disclaim all
                                        liability
                                        for negligence, apart from damages for death, personal injury, or fraudulent
                                        misrepresentation. Your rights as a consumer (if any) are not affected by these
                                        provisions.</ul>
                                </dd>
                            </li><br>
                            <li>
                                <h5>Links</h5>
                                <dd>(a) By using hypertext or other computer links you will be able to access other website
                                    pages on the Internet which are not part of our web pages. We cannot vet or modify any
                                    information provided on such other websites pages, and we hereby exclude all liability
                                    for
                                    the content of other websites or home pages that are linked to our Website. <br>
                                    (b) We shall have no liability in respect of material hyper-linked to our Website which
                                    may
                                    be misleading, inaccurate, defamatory, threatening or obscene or otherwise not in
                                    accordance
                                    with applicable regulations. <br>
                                    (c) The provision by us of a link to another website does not constitute any
                                    authorisation
                                    to access materials held at that location, nor is it evidence of any endorsement by us
                                    of
                                    the material held there.</dd>
                            </li><br>
                            <li>
                                <h5>Trademarks, designs or patents: </h5>
                                <dd>Attica Jewels Private Limited owns various registered trademarks. The display of any of
                                    our trade names, trademarks, designs, patents within the Website Materials does not
                                    imply
                                    that any license has been granted to any third party in respect of the same. All third
                                    party
                                    product or company names, devices, logos, icons, graphics or designs referred in the
                                    Website
                                    Materials are the trademarks of the respective owners and are exhibited only in such a
                                    manner as is intended to be for the benefit of such trademark owners. We intend no
                                    infringement of such trademarks. The appearance or absence of products, services,
                                    companies,
                                    organizations, home pages or other websites on this website does not imply any
                                    endorsement
                                    or non-endorsement thereof by us.</dd>
                            </li><br>
                            <li>
                                <h5>Data Protection Consent</h5>
                                <dd>(a) Information on what (if any) data is held about you can be obtained by contacting us
                                    as
                                    follows:- Contact Us <br>
                                    (b) In accordance with applicable data protection legislation we reserve the right to
                                    charge
                                    a fee for providing such information.</dd>
                            </li><br>
                            <li>
                                <h5>Miscellaneous:</h5>
                                <dd>If you have any questions concerning these Website Terms please write to us at the
                                    e-mail
                                    address specified above. All rights not expressly granted in these terms and conditions
                                    are
                                    expressly reserved.</dd>
                            </li><br>
                            <li>
                                <h5>Assignment: </h5>
                                <dd> Attica Jewels Private Limited shall be permitted to assign, transfer, and subcontract
                                    its
                                    rights and/or obligations under these terms & conditions without any notification or
                                    consent
                                    required. However, you are not be permitted to assign, transfer, or subcontract any of
                                    your
                                    rights and/or obligations under these terms & conditions.</dd>
                            </li><br>
                            <li>
                                <h5>Limitation of Liability:</h5>
                                <dd>In no event shall the Company nor any of its officers, directors and employees, be
                                    liable to
                                    you for anything arising out of or in any way connected with your use of this Website,
                                    whether such liability is under contract, tort or otherwise, and Attica Jewels Private
                                    Limited, including its officers, directors and employees shall not be liable for any
                                    indirect, consequential or special liability arising out of or in any way related to
                                    your
                                    use of this Website.</dd>
                            </li><br>
                            <li>
                                <h5>Severability:</h5>
                                <dd> If any provision of these terms & conditions is found to be unenforceable or invalid
                                    under
                                    any applicable law, such unenforceability or invalidity shall not render these terms &
                                    conditions unenforceable or invalid as a whole, and such provisions shall be deleted
                                    without
                                    affecting the remaining provisions herein.</dd>
                            </li><br>
                            <li>
                                <h5>Indemnity:</h5>
                                <dd>You agree to indemnify us and keep us indemnified us against all claims, charges,
                                    demands,
                                    damages, liabilities, losses and expenses of whatever nature and howsoever arising
                                    (including but not limited to any legal or other professional fees and the cost of
                                    defending
                                    or prosecuting any claim and any loss of profit, goodwill and any other direct or
                                    consequential loss) incurred or suffered by us directly or indirectly by reason of any
                                    act
                                    or omission which you commit in breach of these terms and conditions and the obligations
                                    and
                                    warranties contained in them.</dd>
                            </li><br>
                            <li>
                                <h5>Governing Law & Disputes:</h5>
                                <dd>You irrevocably agree that the courts of New Delhi, India shall have exclusive
                                    jurisdiction
                                    to resolve any dispute or claim of whatever nature arising out of or relating to this
                                    Website, and that the laws of India shall govern such dispute or claim. However, we
                                    retain
                                    the right to bring legal proceedings in any jurisdiction where we believe that
                                    infringement
                                    of our IPR or breach of these Website Terms is taking place or originating. You are
                                    responsible for compliance with any applicable laws of the country from which you are
                                    accessing this Website. We operate this Website from India and make no representation
                                    that
                                    the information contained herein is appropriate or available for use in other locations
                                    outside India.</dd>
                            </li>
                        </dl>

                    </ul>
                </div>
            </div>

            <div class="row my-3 ">
                <div class="col-12 mx-auto">
                    <h5>Coupon Terms & Conditions</h5>
                    <dd>The offer contained in the electronic communication ("eCoupons") is made by Attica Jewels Pvt.
                        Ltd. (also referred to as "we", "our" and "us") and is open to targeted https://www.atticajewels.com
                        registered users ("Users"). These terms and conditions are in addition to the existing Attica Jewels
                        Terms of Use. eCoupons are also not offered to, and shall not be used by, such users who under any
                        statutory obligations are prohibited to use eCoupons. eCoupon is the property of Attica Jewels and
                        Attica Jewels has the right to cancel the eCoupons at will and at any time (including during the
                        validity period of the eCoupon) without giving any prior intimation to the User. eCoupon is a
                        privilege from Attica Jewels and not a right or claim against Attica Jewels. eCoupons can also be
                        cancelled
                        in case the user is in violation of Attica Jewels Terms of Use.</dd> <br>
                    <dd>User using the eCoupons in any manner shall be deemed to have read, understood and accepted these
                        terms and conditions.
                        The value and the mode of using the eCoupon are mentioned in the electronic communication. The
                        validity of eCoupon is subject to the condition that the User remains a registered user and is
                        neither suspended nor in violation of atticajewels Terms of Use.
                        eCoupons can be redeemed only on purchases made on atticajewels.com on those listings which provides
                        for
                        an option of eCoupon payments. eCoupons shall be invalidated in case of rejection of payment by
                        Attica Jewels due to Attica Jewels risk containment measures. eCoupons cannot be used to buy any
                        item
                        which is illegal or prohibited by Terms of Use.
                        eCoupon carries no cash value and cannot be transferred, negotiated or sold and cannot be redeemed
                        against cash. eCoupons cannot be combined with any other coupons or any other offer or gift
                        vouchers/cards or discounts or promotions.
                        One eCoupon can be used only for one purchase irrespective of the value of such purchase and the
                        unutilized or underutilized value of the eCoupons shall be forfeited and the User cannot claim any
                        benefit or a substitute eCoupon in lieu of the same. The purchase value of the item in excess of the
                        value of the eCoupon shall be paid by the User along with using the eCoupon.</dd>
                </div>
            </div>

            <div class="row my-3 ">
                <div class="col-12 mx-auto">
                    <h2 class="text-center">Refund and Return Policy</h2>
                    <br>
                    <h5>Refund Policy</h5>
                    <dd>Products once purchased cannot be returned for refund.
                        Refund will be issued in the following cases upon request from customer either through phone call,
                        email or from order panel:-
                        Cancellation request sent by customer before dispatch
                        After dispatch – refund will be issued once product is received back at operations centre.
                        Failed Delivery / Customer Reject – refund will be issue once product is received back at operations
                        centre.
                        There are certain orders which cannot be cancelled like orders for customized products as per
                        customers requirement. These customized orders cannot be cancelled or refunded.
                        If for any unforeseen circumstance your transaction fails and money is debited, you need to contact
                        us at customercare@atticajewels.com. We will verify and initiate refund if we have received payment.
                        You
                        will receive a refund within 7 to 10 working days.
                        In the highly unlikely event of your order getting lost in transit, we will wait for 15 days to
                        track your lost order. If we are successful in locating the order, we will proceed with delivery. If
                        we are unsuccessful, we will process the refund through the original payment mode used to pay for
                        the order.
                        No other refunds will be entertained</dd>
                    <br>
                    <h5>Returns Policy</h5>
                    <dd>We do not accept returns of products.
                        In the unlikely event that the product delivered is in a damaged condition or a wrong product is
                        delivered, you can call our customer care and request for return of the product. The product should
                        be unused and in the same condition & packaging as you received it. It should be in its original
                        packaging, along with the invoice. In case the certicard in which the product packed is opened or
                        tampered with, return will not be accepted. Our courier partner will collect the order from the
                        address provided by you and will get it back to us.
                        In case you receive a different product, you need to contact our customer service at 1800-313-182182
                        or email at customercare@atticajewels.com. We will do our internal review and suggest next course of
                        action. On successful validation, you can either return the product for a full refund or get the
                        product replaced with the correct product.</dd>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection
